on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "pre_Printing Folder Contents"
        run: ls
      
      - usus: actions/checkout@v3

      - name: "Post_Printing Folder Contents"
        run: ls